### ISSUE TITLE
RuntimeError: cannot defer action events

### ISSUE THREAD

**Issue by morphis** [canonical/governor#2]
Our CI just found a crash in the governor base code:

```
unit-anbox-cloud-governor-0: 16:07:00 ERROR unit.anbox-cloud-governor/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 119, in <module>
    main(AnboxCloudCharm)
  File "/var/lib/juju/agents/unit-anbox-cloud-governor-0/charm/venv.amd64/ops/main.py", line 402, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-anbox-cloud-governor-0/charm/venv.amd64/ops/main.py", line 140, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-anbox-cloud-governor-0/charm/venv.amd64/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-anbox-cloud-governor-0/charm/venv.amd64/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-anbox-cloud-governor-0/charm/venv.amd64/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-anbox-cloud-governor-0/charm/venv.amd64/governor/base.py", line 38, in on_governor_event_action
    self.process_governor_events(event)
  File "/var/lib/juju/agents/unit-anbox-cloud-governor-0/charm/venv.amd64/governor/base.py", line 54, in process_governor_events
    event.defer()
  File "/var/lib/juju/agents/unit-anbox-cloud-governor-0/charm/venv.amd64/ops/charm.py", line 76, in defer
    raise RuntimeError('cannot defer action events')
RuntimeError: cannot defer action events
```

**Comment by DomFleischmann** [comment]
This should be fixed now

**Comment by morphis** [comment]
Thanks @DomFleischmann !
